{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "RetryPolicies.java",
  "functionName": "hasWrappedAccessControlException",
  "functionId": "hasWrappedAccessControlException___e-Exception",
  "sourceFilePath": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java",
  "functionStartLine": 766,
  "functionEndLine": 773,
  "numCommitsSeen": 30,
  "timeTaken": 684,
  "changeHistory": [
    "3d249301f42130de80ab3ecf8c783bb51b0fa8a3"
  ],
  "changeHistoryShort": {
    "3d249301f42130de80ab3ecf8c783bb51b0fa8a3": "Yintroduced"
  },
  "changeHistoryDetails": {
    "3d249301f42130de80ab3ecf8c783bb51b0fa8a3": {
      "type": "Yintroduced",
      "commitMessage": "HADOOP-16683. Disable retry of FailoverOnNetworkExceptionRetry in case of wrapped AccessControlException. Contributed by Adam Antal\n",
      "commitDate": "09/11/19 6:43 AM",
      "commitName": "3d249301f42130de80ab3ecf8c783bb51b0fa8a3",
      "commitAuthor": "Szilard Nemeth",
      "diff": "@@ -0,0 +1,8 @@\n+  private static boolean hasWrappedAccessControlException(Exception e) {\n+    Throwable throwable \u003d e;\n+    while (!(throwable instanceof AccessControlException) \u0026\u0026\n+        throwable.getCause() !\u003d null) {\n+      throwable \u003d throwable.getCause();\n+    }\n+    return throwable instanceof AccessControlException;\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private static boolean hasWrappedAccessControlException(Exception e) {\n    Throwable throwable \u003d e;\n    while (!(throwable instanceof AccessControlException) \u0026\u0026\n        throwable.getCause() !\u003d null) {\n      throwable \u003d throwable.getCause();\n    }\n    return throwable instanceof AccessControlException;\n  }",
      "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java"
    }
  }
}